### ISSUE TITLE
Allow usage query variable and hash in `template` option

### ISSUE THREAD

**Issue by alexander-akait** [geut/postcss-copy#44]
Example allow:

```
[path]/[name].[ext]?hash=[hash]#[hash]
```

**Comment by tinchoz49** [comment]
added new properties tags for the templates.

`[query]` is the full query string
`[qparams]` is the params without the char '?'
`[qhash]` is the hash without the char '#'

This was a breaking change for the template name, since in old versions of postcss-copy the file name worked with the extra query string implicit, now it's must be setted explicit.

e.g. `[path]/[name].[ext][query]`
