### ISSUE TITLE
glob src option 

### ISSUE THREAD

**Issue by shuhrat** [geut/postcss-copy#51]
It would be great, if `src` will accept globs

**Comment by tinchoz49** [comment]
I think the same, it's a good feature!

**Comment by tinchoz49** [comment]
Hi @shuhrat how are you?

I was thinking about this feature and I came to the conclusion that the `src` option is doing the same work that `basePath` in `postcss-url` (a nice plugin where `postcss-copy` started as an inside function). 
In the `basePath` option you can define a string path or an array of string path like `src` and i think is really simple approach and like try to keep that path in this plugin.

So, what do you think if first I change the `src` option to `basePath` because describe in a better way what the option does and second, we can add an example in the readme using globs with postcss-copy.

**Comment by tinchoz49** [comment]
Hi @shuhrat how are you? I was thinking about this feature and the performance issues on running node-glob. 

I think is better if we keep the plugin simple since this kind of feature is easier to implement by the user.
If you want we can add an example in the README

**Comment by tinchoz49** [comment]
closing this issue because there wasn't any activity
