### ISSUE TITLE
Allow `src` option to be optional and default  to './'

### ISSUE THREAD

**Issue by shuhrat** [geut/postcss-copy#52]
Now option `src` is required. 
But what if someone want to copy all files?
Of course, `src: '/'` is an option as workaround, but it looks like a hack)

Maybe better to define `src` as an optional?

**Comment by tinchoz49** [comment]
I'm working on the next release with some breaking changes in the API and with this feature added. :smile:
Everything with the objective of simplify the functionality of postcss-copy to do one thing and do it well.

`src` is going to be changed to `basePath`. It's more clear to me and describe in a better way what is the purpose of this option.

`inputPath` was removed since it was an option to fix issues related to other postcss plugin and I don't think that postcss-copy is in charge of fixing it.

`keepRelativePath` function was removed in favor of the flag `preservePath`. It's more simple than have to play with the internal paths.
